name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Run tests
        run: forge test

      - name: Create updated snapshot
        run: forge snapshot

      - name: Check gas snapshots with tolerance
        run: forge snapshot --check --tolerance 10

      - name: Upload updated snapshot as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gas-snapshot
          path: .gas-snapshot
          if-no-files-found: error
